## Selecting Elements and Groups of Elements from an Array

In [1]:
# Import the numpy library
import numpy as np

In [2]:
# Generate values for array
arr = np.arange(0,11)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# Select the second element in the above array
arr[1]

1

In [4]:
# Use Slice notation to select a range within the array
arr[:4]

array([0, 1, 2, 3])

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
# Select everything at a position to the end of the array
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### Broadcasting 

In [8]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
# Redo original array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Slicing Arrays

In [11]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [12]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [14]:
# Oh No, the broadcasting of 99 has changed the original array***
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### How to Copy Arrays

In [15]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
# Now change copy and watch as the original remains the same
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### How to index 2-D arrays (matrixes)

In [18]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [19]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
# Use double bracket notation to grab the element 25
arr_2d[1][1]

25

In [21]:
# Use double bracket notation to grab the element 40
arr_2d[2][1]

40

In [22]:
# Use single bracket notation with comma to grab 30
arr_2d[1,2]

30

### How to select chunks or an array

In [23]:
# Select only 10, 15, 25 and 30
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [24]:
# Grab 20, 25, 35, 40
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

### How to create Conditional Selections

In [26]:
# Create practice array
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[0]

1

In [29]:
bool_arr = arr > 5

In [30]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [31]:
# Run conditional selection where boolean values are true
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [32]:
# Typical way to do this is as follows
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [33]:
# Identify all of the elements that are less than 3
arr[arr<3]

array([1, 2])

### Practice with Conditional Statements

In [34]:
# Create 2-d Array
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [35]:
# Use Bracket Notation to grab unique chunks 23, 24, 25, 26, 33, 34, 35, 36
arr_2d[2:4,3:7]


array([[23, 24, 25, 26],
       [33, 34, 35, 36]])