## NumPy Arrays

### Arrays

In [3]:
# Create a list object
my_lst = [1,2,3,4,5]
my_lst

[1, 2, 3, 4, 5]

In [2]:
# Import Numpy
import numpy as np

In [6]:
# Convert list to an 1-d array
np_arr = np.array(my_lst)
np_arr

array([1, 2, 3, 4, 5])

In [7]:
# Create a 2-dimensional Array
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
# Convert list of lists into 2-d array
np_mat = np.array(my_mat)
np_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# Use NumPy built in array generator
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# create array with zeros
