## Introduction to Machine Learning

### Step (1) Import necessary dependencies

In [8]:
# Import numpy to generate test data

import numpy as np


In [6]:
# Import the model family and specify the estimator we would like to use

from sklearn.cross_validation import train_test_split

### Step (2) Create test data to work with

In [21]:
# Create test data that has inputs and target data
# arange creates a list of values from 0 to 20
# reshape alters that list to be displayed as ten rows with two columns
# range provides a tuple with values starting at 0 and ending at 5

# X = Features
# y = Labels

# X and y must have the same amount of rows

X, y = np.arange(20).reshape(10,2), range(10)

In [22]:
X

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [23]:
list(y)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### Step (3) Split data into Test and Training sets

In [24]:
# Split the data 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [26]:
# Observer the Training and Test Splits

X_train

array([[12, 13],
       [16, 17],
       [ 2,  3],
       [14, 15],
       [18, 19],
       [ 8,  9],
       [10, 11]])

In [27]:
# Observer the Training and Test Splits

y_train

[6, 8, 1, 7, 9, 4, 5]

In [28]:
# Observer the Training and Test Splits

X_test

array([[0, 1],
       [4, 5],
       [6, 7]])

In [29]:
# Observer the Training and Test Splits

y_test

[0, 2, 3]